set "BUILD_TYPE=%1"
set "TARGET_IDE=%2"

rem if %BUILD_TYPE%==""(
rem 	set "BUILD_TYPE=Release"
rem )

cmake -DFTXUI_BUILD_DOCS=OFF -DFTXUI_BUILD_EXAMPLES=OFF -DFTXUI_ENABLE_INSTALL=OFF -DCMAKE_BUILD_TYPE="%BUILD_TYPE%" -G "TARGET_IDE" -S . -B projects/ --fresh
